@url= http://localhost:7033

### READ users 
GET {{url}}/users
content-type: application/json


### CREATE user with same password
POST {{url}}/users/create
content-type: application/json
 
{
    "username": "333",
    "password1": "12345678",
    "password2": "12345678",
    "email": "test@mail.com"
}



### CREATE user with same password
POST {{url}}/users/signup
content-type: application/json
 
{
    "username": "NewDB",
    "password1": "12345678",
    "password2": "12345678",
    "email": "test9@mail.com"
}

### CREATE user with different password
POST {{url}}/users/signup
content-type: application/json
 
{
    "username": "TEST93",
    "password1": "1234564",
    "password2": "12345678",
    "email": "test9@mail.com"
}



### user login
POST {{url}}/users/login
content-type: application/json

{
    "username": "NewDB",
    "password": "12345678"
}


### LOGIN user false
POST {{url}}/users/login
content-type: application/json
 
{
    "userName": "g00g",
    "password": "12345678"
}


### user logout
GET {{url}}/users/logout
content-type: application/json